// src/lib/features/fridge/search/FoodSearchResults.vue
<script setup lang="ts">
import type { Food } from '@/lib/model';
import EditIcon from '@/lib/ui/icon/EditIcon.vue';
import LogItem from '@/lib/ui/list/LogItem.vue';

const emit = defineEmits<{
  (e: "loadMore"): void,
  (e: "itemSelected", item: Food): void
}>();

const props = defineProps<{
  items: Food[]
}>();

function handleScroll(e: Event) {
  const el = e.target as HTMLElement;

  // vypocet toho zda uz doscrolloval dolu
  const isBottom = el.scrollTop + el.clientHeight >= el.scrollHeight - 200;
  if (isBottom) {
    setTimeout(() => {
      emit("loadMore");
    }, 50);
  }
}
</script>

<template>
  <ul @scroll="handleScroll">
    <hr />
    <template v-for="item in props.items" :key="item.id">
      <li>
        <LogItem :name="item.name" :subtext="item.brand" :kcal="item.macronutrients.kcal" :itemType="item.type"
          @click="emit('itemSelected', item)" />
      </li>
      <hr />
    </template>
  </ul>
</template>

<style scoped>
ul {
  flex-grow: 1;
  overflow-y: auto;
}

hr {
  border: 1px solid var(--secondary-color);
}
</style>

// src/lib/features/search/FoodSearchResults.svelte
<script lang="ts">
    import type { Food } from "../../model";
    import RecipeIcon from "../ui/icon/RecipeIcon.svelte";
    import LogItem from "../ui/list/LogItem.svelte";

    // prijmout itemy z rodice
    let { items = [] as Food[], onLoadMore } = $props();

    function handleScroll(e: Event) {
        const el = e.target as HTMLElement;

        // vypocet toho zda uz doscrolloval dolu
        const isBottom =
            el.scrollTop + el.clientHeight >= el.scrollHeight - 200;
        if (isBottom && onLoadMore) {
            setTimeout(onLoadMore, 50);
        }
    }
</script>

<ul onscroll={handleScroll}>
    <hr />
    {#if items.length > 0}
        {#each items as item}
            <li>
                <LogItem
                    Icon={RecipeIcon}
                    name={item.name}
                    subtext={item.brand ?? ""}
                    kcal={item.macronutrients.kcal}
                />
            </li>
            <hr />
        {/each}
    {/if}
</ul>

<style>
    ul {
        flex-grow: 1;
        overflow-y: auto;
    }

    hr {
        border: 1px solid var(--secondary-color);
    }
</style>
