// src/lib/ui/form/input/labeled/LabeledInput.vue
<script setup lang="ts">
interface Props {
  label: string;
  name?: string;
  type: string;
  step?: string;
}

const props = defineProps<Props>();

const model = defineModel<string | number | null>();
</script>

<template>
  <div>
    <label :for="props.name">{{ props.label }}</label>
    <input :type="props.type" :name="props.name" :step="props.step" v-model="model" />
  </div>
</template>

<style scoped>
div {
  display: flex;
}

label {
  flex: 1;
}

input {
  flex: 2;
}
</style>

// src/lib/ui/form/input/LabeledInput.svelte
<script lang="ts">
    interface Props {
        label: string;
        name: string;
        value: string;
        type: string;
    }

    let { label, name, value, type }: Props = $props();
</script>

<div>
    <label for={name}>{label}</label>
    <input {type} {name} {value} />
</div>

<style>
    div {
        display: flex;
    }

    label {
        flex: 1;
    }

    input {
        flex: 2;
    }
</style>
