// src/features/fridge/search/Search.vue
<script setup lang="ts">
import { FoodSearchFilter } from "@/api/food/food.filter";
import { useFoodSelectionStore } from "@/stores/food-selection.store";
import OutlineButton from "@/ui/action/OutlineButton.vue";
import SearchInput from "@/ui/form/input/SearchInput.vue";
import AddIcon from "@/ui/icon/AddIcon.vue";
import ListLoadingEffect from "@/ui/list/ListLoadingEffect.vue";
import TabSelection from "@/ui/list/TabSelection.vue";
import { onMounted, ref, watch } from "vue";
import { deleteFood, getFoods } from "../../../api";
import NoResults from "./components/NoResults.vue";
import FoodSearchResults from "./FoodSearchResults.vue";
import type { Food } from "@/model";

const emit = defineEmits<{
  (e: "itemSelected", item: Food): void;
}>();

const TIMEOUT_MS = 300;

const foodItems = ref<Food[]>([]);
const query = ref("");
const searching = ref(false);

const page = ref(0); // vychozi load je 0
const hasMore = ref(true);

const { openFoodForm } = useFoodSelectionStore();

// debounce timer
let timer: ReturnType<typeof setTimeout>;

async function search(currentQuery: string, newQuery: boolean) {
  if (newQuery) {
    page.value = 0;
  } else {
    page.value += 1;
  }

  searching.value = true;
  if (newQuery) foodItems.value = [];

  const filter = getActiveFilter();
  try {
    const response = await getFoods(currentQuery, filter, page.value);
    foodItems.value = [...foodItems.value, ...response.foodItems];
    hasMore.value = response.hasMore;
  } catch (e) {
    console.error("Searching food items failed:", e);
    if (page.value > 0) page.value -= 1;
  } finally {
    searching.value = false;
  }
}

watch(query, (newQuery) => {
  clearTimeout(timer);
  timer = setTimeout(() => search(newQuery, true), TIMEOUT_MS);
});

async function loadMore() {
  if (searching.value || !hasMore.value) return;
  search(query.value, false);
}

async function triggerDelete(item: Food) {
  // hned smazat z UI
  foodItems.value = foodItems.value.filter((food) => food.id !== item.id);
  try {
    await deleteFood(item);
  } catch (e) {
    console.error("Failed to delete food item:", e);
  }
}

// Filters
const searchFilters = ["All", "Private", "Public"];
const selectedSearchFilter = ref<string>("All");
const getActiveFilter = () => {
  switch (selectedSearchFilter.value) {
    case "Private":
      return FoodSearchFilter.PRIVATE;
    case "Public":
      return FoodSearchFilter.PUBLIC;
    default:
      return FoodSearchFilter.ALL;
  }
};

watch(query, (newQuery) => {
  clearTimeout(timer);
  timer = setTimeout(() => search(newQuery, true), TIMEOUT_MS);
});

watch(selectedSearchFilter, () => {
  search(query.value, true);
});

onMounted(() => {
  search(query.value, true);
});
</script>

<template>
  <div class="col search-controls">
    <TabSelection v-model="selectedSearchFilter" :options="searchFilters" />
    <div class="row actions center stretch-v">
      <SearchInput class="search" v-model="query" placeholder="Search foods" />
      <OutlineButton class="plus-btn" @click="openFoodForm()">
        <AddIcon></AddIcon>
      </OutlineButton>
    </div>
  </div>
  <ListLoadingEffect v-if="searching && foodItems.length === 0" />
  <FoodSearchResults
    v-else-if="foodItems.length > 0"
    :items="foodItems"
    @loadMore="loadMore"
    @itemSelected="(item: Food) => emit('itemSelected', item)"
    @itemDeleted="triggerDelete"
  />
  <NoResults class="offcenter" v-else />
</template>

<style scoped>
.search-controls {
  gap: 0.25rem;
  .actions {
    padding: 0.5rem;
    gap: 0.5rem;
    height: 4rem;
  }
  .search {
    flex: 1;
    min-width: 0;
  }
  .plus-btn {
    aspect-ratio: 1;
    height: 100%;
    width: fit-content;
    flex-shrink: 0;
  }
}

@media (min-width: 2560px) {
  .search-controls {
    .actions {
      height: 6rem;
    }
    .search {
      padding-left: 2rem;
      font-size: 150%;
    }
  }
}
</style>

// src/lib/features/fridge/search/Search.svelte
<script lang="ts">
  import { getFoodSearchResults } from "../../../api";
  import type { Food } from "../../../model";
  import SearchInput from "../../../ui/form/input/SearchInput.svelte";
  import ListLoadingEffect from "../../../ui/list/ListLoadingEffect.svelte";
  import TabSelection from "../../../ui/list/TabSelection.svelte";
  import FoodSearchResults from "./FoodSearchResults.svelte";

  let { onItemSelected } = $props();

  const TIMEOUT_MS = 300;

  let foodItems = $state<Food[]>([]);
  let query = $state("");
  let searching = $state(false);

  let page = $state(0); // vychozi load je 0
  let hasMore = $state(true);

  // debounce timer
  let timer: ReturnType<typeof setTimeout>;

  async function search(currentQuery: string, newQuery: boolean) {
    if (newQuery) {
      page = 0;
    } else {
      page += 1;
    }

    searching = true;

    try {
      const response = await getFoodSearchResults(currentQuery, page);
      hasMore = response.hasMore;
      foodItems = newQuery
        ? response.foodItems
        : [...foodItems, ...response.foodItems];
    } catch (e) {
      console.error("Searching food items failed:", e);
      if (page > 0) page -= 1;
    } finally {
      searching = false;
    }
  }

  $effect(() => {
    const currentQuery = query; // potreba precist drive nez v async blocku!!!
    clearTimeout(timer);
    timer = setTimeout(async () => search(currentQuery, true), TIMEOUT_MS);
  });

  async function loadMore() {
    if (searching || !hasMore) return;
    search(query, false);
  }
</script>

<!-- TODO az bude user mit ucet tak vyhledavat podle typu
    Public = SOMA author
    Private = pouze jeho vlastni
    All = public + private
-->
<div class="search-controls">
  <TabSelection selected="All" options={["All", "Private", "Public"]} />
  <TabSelection selected="All" options={["All", "Foods", "Recipes"]} />
  <SearchInput bind:value={query} placeholder="Search foods" />
</div>
{#if searching && foodItems.length === 0}
  <ListLoadingEffect />
{:else if !searching && foodItems.length === 0}
  <div class="center-content offset-center-up">
    <span>No items found</span>
  </div>
{:else}
  <FoodSearchResults items={foodItems} onLoadMore={loadMore} {onItemSelected} />
{/if}

<style>
  /* aby nacitaci column food search results nezmackla input a tab selection */
  .search-controls {
    display: flex;
    flex-direction: column;
    flex-shrink: 0;
  }
</style>
