// src/lib/ui/form/input/labeled/LabeledNumberInput.vue
<!-- LabeledNumberInput -->
<script setup lang="ts">
import LabeledInput from "./LabeledInput.vue";

interface Props {
  label: string;
  name?: string;
  step?: string;
}

// zklonovane props
const props = withDefaults(defineProps<Props>(), {
  step: "0.1"
})

const inputModel = defineModel<number | string | null>("value");
</script>

<template>
  <LabeledInput type="number" v-bind="props" v-model.number="inputModel" />
</template>

// src/lib/ui/form/input/labeled/LabeledNumberInput.svelte
<!-- LabeledNumberInput -->
<script lang="ts">
  import LabeledInput from "./LabeledInput.svelte";

  interface Props {
    label: string;
    name?: string | null;
    value: any;
    step?: string;
    oninput: (e: Event) => void;
  }

  let {
    label,
    name,
    value = $bindable(""),
    step = "0.1",
    oninput,
  }: Props = $props();
</script>

<LabeledInput type="number" {label} {name} {value} {oninput} {step} />
