// src/lib/ui/list/TabSelection.vue
<script setup lang="ts">
const selected = defineModel<string>();
const props = defineProps<{
  options?: string[]
}>();

const onOptionSelected = (opt: string) => selected.value = opt;
</script>

<template>
  <div>
    <button v-for="opt in props.options" :key="opt" :class="{ selected: opt == selected }"
      @click="onOptionSelected(opt)">
      {{ opt }}
    </button>
  </div>
</template>

<style scoped>
div {
  display: flex;
  flex-direction: row;
}

button {
  background-color: var(--tertiary-color);
  height: 2rem;
  width: 100%;
}

button:hover {
  background-color: var(--quadratery-color);
  cursor: pointer;
}

button.selected {
  background-color: var(--subtle-color);
}
</style>

// src/lib/features/ui/TabSelection.svelte
<script lang="ts">
    let { selected = $bindable(), options = [] } = $props();
</script>

<div>
    {#each options as opt}
        <button
            class:selected={opt === selected}
            onclick={() => (selected = opt)}
        >
            {opt}
        </button>
    {/each}
</div>

<style>
    div {
        display: flex;
        flex-direction: row;
    }

    button {
        background-color: var(--tertiary-color);
        height: 2rem;
        width: 100%;
    }

    button:hover {
        background-color: var(--quadratery-color);
        cursor: pointer;
    }

    button.selected {
        background-color: var(--subtle-color);
    }
</style>
