// src/lib/features/ui/TabSelection.svelte
<script lang="ts">
    let { selected = $bindable(), options = [] } = $props();
</script>

<div>
    {#each options as opt}
        <button
            class:selected={opt === selected}
            onclick={() => (selected = opt)}
        >
            {opt}
        </button>
    {/each}
</div>

<style>
    div {
        display: flex;
        flex-direction: row;
    }

    button {
        background-color: var(--tertiary-color);
        height: 2rem;
        width: 100%;
    }

    button:hover {
        background-color: var(--quadratery-color);
        cursor: pointer;
    }

    button.selected {
        background-color: var(--subtle-color);
    }
</style>

// src/ui/list/TabSelection.vue
<script setup lang="ts">
const selected = defineModel<string>();
const props = defineProps<{
  options?: string[];
}>();

const onOptionSelected = (opt: string) => (selected.value = opt);
</script>

<template>
  <div class="row stretch-h">
    <button
      v-for="opt in props.options"
      :key="opt"
      :class="{ active: opt == selected }"
      @click="onOptionSelected(opt)"
    >
      {{ opt }}
    </button>
  </div>
</template>

<style scoped>
button {
  padding: 0;

  width: 100%;
  height: 2.75rem;

  border: none;
  border-bottom: 2px solid transparent;

  font-size: 80%;
  font-weight: 800;
  letter-spacing: 0.15rem;

  color: var(--text-dim);
  background-color: transparent;

  transition: all 0.2s;
  cursor: pointer;

  @media (min-width: 2560px) {
    height: 4rem;
    font-size: 150%;
  }
}

button:hover {
  color: var(--text-main);
  background-color: var(--bg-surface);
  border-bottom: 2px solid var(--border-main);
}

button.active {
  color: var(--color-accent);
  border-bottom: 2px solid var(--color-accent);
}
</style>
