// src/lib/features/log/LogSection.vue
<!-- Center section displaying DailyLog and forms for adding and updating log entries. -->
<script setup lang="ts">
import { useLogSelectionStore } from "@/lib/stores";
import type { LogEntry } from "../../model";
import LogEntryForm from "./crud/LogEntryForm.vue";
import DailyLog from "./overview/DailyLog.vue";

const logSelectionStore = useLogSelectionStore();

const showOverview = () => logSelectionStore.closeLogForm();
const showEdit = (entry: LogEntry) => logSelectionStore.openLogForm(entry.item, entry);
</script>

<template>
  <LogEntryForm v-if="logSelectionStore.activeLogSelection" @finished="showOverview"
    :trackable="logSelectionStore.activeLogSelection.trackable"
    :entry="logSelectionStore.activeLogSelection.entry ?? undefined" />
  <DailyLog v-else @itemSelected="showEdit" />
</template>

// src/lib/features/log/LogSection.svelte
<!-- Center section displaying DailyLog and forms for adding and updating log entries. -->
<script lang="ts">
  import type { LogEntry } from "../../model";
  import {
    activeLogSelection,
    closeLogForm,
    openLogForm,
  } from "../../stores/ui.store";
  import LogEntryForm from "./crud/LogEntryForm.svelte";
  import DailyLog from "./overview/DailyLog.svelte";

  const isOnOverview = $derived(!$activeLogSelection);

  const showOverview = () => closeLogForm();
  const showEdit = (entry: LogEntry) => openLogForm(entry.item, entry);
</script>

{#if isOnOverview}
  <DailyLog onItemSelected={showEdit} />
{:else if $activeLogSelection}
  <LogEntryForm
    onFinished={showOverview}
    trackable={$activeLogSelection.trackable}
    entry={$activeLogSelection.entry ?? undefined}
  />
{/if}
