// src/lib/features/log/DailyLog.svelte
<script lang="ts">
  import TransparentButton from "../../ui/action/TransparentButton.svelte";
  import LogItem from "../../ui/list/LogItem.svelte";

  import { getLogEntries } from "../../api/log/log.api";
  import type { LogEntry } from "../../model";
  import BackArrowIcon from "../../ui/icon/BackArrowIcon.svelte";
  import ForwardArrowIcon from "../../ui/icon/ForwardArrowIcon.svelte";
  import ListLoadingEffect from "../../ui/list/ListLoadingEffect.svelte";

  interface Props {
    onItemSelected: (entry: LogEntry) => void;
  }
  let { onItemSelected }: Props = $props();

  let loadingEntries = $state(true);
  let logEntries = $state<LogEntry[]>([]);
  getLogEntries()
    .then((entries: LogEntry[]) => {
      logEntries = entries;
    })
    .finally(() => {
      loadingEntries = false;
    });
</script>

<nav class="apart center">
  <div class="left center">
    <TransparentButton
      onclick={() => null}
      Icon={BackArrowIcon}
      class="date-button"
    />
    <h3>03.06.2026</h3>
  </div>
  <TransparentButton
    onclick={() => null}
    Icon={ForwardArrowIcon}
    class="date-button"
  />
</nav>
<div>
  <span>daily targets progress bar</span>
</div>
{#if loadingEntries}
  <ListLoadingEffect />
{:else}
  <ul>
    <hr />
    {#each logEntries as entry}
      <li>
        <LogItem
          name={entry.item.name}
          subtext={`${entry.quantity} ${entry.servingName}`}
          itemType={entry.item.type}
          onclick={() => onItemSelected(entry)}
        />
      </li>
      <hr />
    {/each}
  </ul>
{/if}

<style>
  nav {
    padding: 1rem;
  }

  :global(.date-button) {
    width: 2.5rem;
  }

  ul {
    flex-grow: 1;
    overflow-y: auto;
  }

  hr {
    border: 1px solid black;
  }
</style>

// src/lib/features/log/overview/DailyLog.vue
<script setup lang="ts">
import { ref } from "vue";
import { getLogEntries } from "../../../api/log/log.api";
import type { LogEntry } from "../../../model";
import TransparentButton from "@/lib/ui/action/TransparentButton.vue";
import BackArrowIcon from "@/lib/ui/icon/BackArrowIcon.vue";
import ForwardArrowIcon from "@/lib/ui/icon/ForwardArrowIcon.vue";
import LogItem from "@/lib/ui/list/LogItem.vue";

const emit = defineEmits<{
  (e: "itemSelected", entry: LogEntry): void
}>();

const loadingEntries = ref(true);
const logEntries = ref<LogEntry[]>([]);
getLogEntries()
  .then((entries: LogEntry[]) => {
    logEntries.value = entries;
  })
  .finally(() => {
    loadingEntries.value = false;
  });
</script>

<template>
  <nav class="apart center">
    <div class="left center">
      <TransparentButton @click="() => null">
        <BackArrowIcon />
      </TransparentButton>
      <h3>03.06.2026</h3>
    </div>
    <TransparentButton @click="() => null">
      <ForwardArrowIcon />
    </TransparentButton>
  </nav>
  <TargetsProgress :date="new Date()" />
  <ListLoadingEffect v-if="loadingEntries" />
  <ul v-else>
    <hr />
    <template v-for="entry in logEntries">
      <li>
        <LogItem :name="entry.item.name" :subtext="`${entry.quantity} ${entry.servingName}`" :itemType="entry.item.type"
          @click="emit('itemSelected', entry)" />
      </li>
      <hr />
    </template>
  </ul>
</template>

<style scoped>
nav {
  padding: 1rem;
}

:deep(.date-button) {
  width: 2.5rem;
}

ul {
  flex-grow: 1;
  overflow-y: auto;
}

hr {
  border: 1px solid black;
}
</style>
