// src/features/log/overview/targets/TargetsProgress.vue
<script setup lang="ts">
import { NUTRIENT_DISPLAY_NAMES, roundNutrient } from "@/constants";
import type { DailyTargets } from "@/model";
import { useTargetsStore } from "@/stores";
import { useSummaryStore } from "@/stores/summary.store";
import { computed } from "vue";

interface Props {
  date: Date;
}
const props = defineProps<Props>();

const shownTargetsKeys: (keyof DailyTargets)[] = [
  "kcal",
  "protein",
  "fats",
  "carbs",
]; // optionally enabled targets (prepared for the future)

const { targetsState } = useTargetsStore();
const { summaryState } = useSummaryStore();

// extracnuti dat pro template
const targets = computed(() => {
  return shownTargetsKeys.map((key) => {
    const max = targetsState.dailyTargets?.[key];
    const current = summaryState.dailySummary?.[key] ?? 0;
    return {
      name: NUTRIENT_DISPLAY_NAMES[key] ?? key,
      current: roundNutrient(current),
      max: max ? roundNutrient(max) : null,
      percentage: max ? (current / max) * 100 : 0,
    };
  });
});
</script>

<template>
  <div class="col stretch-h middle container">
    <template v-for="target in targets" :key="target.name">
      <div class="target apart center">
        <span>{{ target.name }}</span>
        <span>
          {{
            target.max != null
              ? `${target.current} / ${target.max}`
              : target.current
          }}
        </span>
      </div>
      <div class="progress-container">
        <div
          class="progress-bar"
          :style="{ width: target.percentage + '%' }"
        ></div>
      </div>
    </template>
  </div>
</template>

<style scoped>
.container {
  margin: 1rem;
  padding: 1rem;
  gap: 0.5rem;
  background-color: var(--bg-surface);
  border-radius: 0.5em;

  .target {
    span:first-child {
      font-size: 100%;
    }
    span:last-child {
      font-size: 90%;
      color: var(--text-dim);
    }
  }

  .progress-container {
    height: 0.4rem;
    border-radius: 9999px;
    width: 100%;
    background-color: var(--border-main);
    overflow: hidden;

    .progress-bar {
      height: 100%;
      background-color: var(--color-accent);
      transition: width 0.4s cubic-bezier(0.4, 0, 0.2, 1);
    }
  }
}

@media (min-width: 2560px) {
  .container {
    gap: 1rem;
    .target {
      span:first-child {
        font-size: 150%;
      }
      span:last-child {
        font-size: 130%;
      }
    }
    .progress-container {
      height: 0.7rem;
    }
  }
}
</style>

// src/lib/features/log/overview/targets/TargetsProgress.svelte
<script lang="ts">
  import { getDailySummary, getDailyTargets } from "../../../../api";
  import { NUTRIENT_NAMES } from "../../../../constants/ui.const";
  import type { DailySummary, DailyTargets } from "../../../../model";
  import ListLoadingEffect from "../../../../ui/list/ListLoadingEffect.svelte";

  interface Props {
    date: Date;
  }
  let { date }: Props = $props();

  const shownTargetsKeys: (keyof DailyTargets)[] = ["kcal", "protein"];

  let dailyTargets = $state<DailyTargets | null>(null);
  let dailySummary = $state<DailySummary | null>(null);

  let loadingTargets = $state(true);
  let loadingSummary = $state(true);

  getDailyTargets()
    .then((targets) => {
      dailyTargets = targets;
    })
    .finally(() => {
      loadingTargets = false;
    });

  getDailySummary(date)
    .then((summary) => {
      dailySummary = summary;
    })
    .finally(() => {
      loadingSummary = false;
    });

  let isLoading = $derived(loadingTargets || loadingSummary);

  let targets = $derived(
    shownTargetsKeys.map((key) => ({
      name: NUTRIENT_NAMES[key] ?? key,
      current: dailySummary?.[key] ?? 0,
      max: dailyTargets?.[key] ?? null,
    })),
  );
</script>

{#if isLoading}
  <ListLoadingEffect />
{:else}
  <div class="col stretch-h middle">
    {#each targets as target}
      <div class="apart">
        <span>{target.name}</span>
        <span>
          {target.max != null
            ? `${target.current} / ${target.max}`
            : target.current}
        </span>
      </div>
      {#if target.max != null}
        <progress value={target.current} max={target.max}></progress>
      {/if}
    {/each}
  </div>
{/if}
