// src/lib/features/fridge/FridgeSection.svelte
<!-- Left section for searching food / recipes, adding and updating food items or recipes. -->
<script lang="ts">
  import type { Food } from "../../model";
  import { openLogForm } from "../../stores/ui.store";
  import FoodForm from "./crud/FoodForm.svelte";
  import { View } from "./fridge.helper";
  import Search from "./search/Search.svelte";

  let view = $state<string>(View.SEARCH);
  let selectedFood = $state<Food | null>(null);

  const showSearch = () => (view = View.SEARCH);
  const showAdd = () => (view = View.ADD); // TODO jeste nevim kde na to bude button
  const showEdit = (food: Food) => {
    selectedFood = food;
    view = View.EDIT;
  };

  const triggerAddEntry = (food: Food) => {
    openLogForm(food);
  };
</script>

{#if view === View.SEARCH}
  <Search onItemSelected={triggerAddEntry} />
{:else if view === View.ADD}
  <FoodForm onFinished={showSearch} />
{:else if view === View.EDIT}
  <FoodForm onFinished={showSearch} food={selectedFood} />
{/if}

// src/features/fridge/FridgeSection.vue
<!-- Left section for searching food / recipes, adding and updating food items or recipes. -->
<script setup lang="ts">
import type { Food } from "@/model";
import { useLogStore } from "@/stores";
import { useFoodSelectionStore } from "@/stores/food.store";
import AddFoodForm from "./crud/AddFoodForm.vue";
import EditFoodForm from "./crud/EditFoodForm.vue";
import "./search/Search.vue";
import Search from "./search/Search.vue";
import { useMobile } from "@/stores/mobile.store";

const logSelectionStore = useLogStore();
const { foodSelectionState, closeFoodForm } = useFoodSelectionStore();
const { setActiveSection } = useMobile();

const triggerAddEntry = (food: Food) => {
  logSelectionStore.openLogForm(food);
  setActiveSection("log");
};
</script>

<template>
  <Search
    v-if="!foodSelectionState.isFormOpen"
    @itemSelected="triggerAddEntry"
  />
  <AddFoodForm
    v-else-if="!foodSelectionState.selectedFood"
    @finished="closeFoodForm"
  />
  <EditFoodForm
    v-else
    :food="foodSelectionState.selectedFood"
    @finished="closeFoodForm"
  />
</template>
